// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2_EFCORE.Data;

#nullable disable

namespace TP2_EFCORE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP2_EFCORE.Models.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoursPrealableId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DureeDuCoursMinutes")
                        .HasColumnType("int");

                    b.Property<int>("NombreMaximalSuggere")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoursPrealableId");

                    b.ToTable("Cours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ces nageurs débutants deviendront confortables à sauter dans l’eau.",
                            DureeDuCoursMinutes = 30,
                            NombreMaximalSuggere = 5,
                            Titre = "Nageur 1"
                        },
                        new
                        {
                            Id = 2,
                            CoursPrealableId = 1,
                            Description = "Ces débutants aux habiletés plus avancées sauteront en eau plus profonde.",
                            DureeDuCoursMinutes = 30,
                            NombreMaximalSuggere = 5,
                            Titre = "Nageur 2"
                        },
                        new
                        {
                            Id = 3,
                            CoursPrealableId = 2,
                            Description = "Ces jeunes nageurs feront des plongeons, des roulades avant dans l’eau et des appuis renversés.",
                            DureeDuCoursMinutes = 30,
                            NombreMaximalSuggere = 5,
                            Titre = "Nageur 3"
                        },
                        new
                        {
                            Id = 4,
                            CoursPrealableId = 3,
                            Description = "Ces nageurs intermédiaires nageront 5 m sous l’eau et ils feront des longueurs au crawl.",
                            DureeDuCoursMinutes = 50,
                            NombreMaximalSuggere = 6,
                            Titre = "Nageur 4"
                        },
                        new
                        {
                            Id = 5,
                            CoursPrealableId = 4,
                            Description = "Ces nageurs maîtriseront les plongeons à fleur d'eau, les sauts groupés (en boule)",
                            DureeDuCoursMinutes = 50,
                            NombreMaximalSuggere = 6,
                            Titre = "Nageur 5"
                        });
                });

            modelBuilder.Entity("TP2_EFCORE.Models.CoursGroupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("MoniteurId")
                        .HasColumnType("int");

                    b.Property<int>("MoniteurParDefautId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroGroupe")
                        .HasColumnType("int");

                    b.Property<int>("PiscineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("MoniteurId");

                    b.HasIndex("PiscineId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursGroupeId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoursGroupeId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Moniteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NoLicence")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Moniteurs");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.OccurenceCours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupeId")
                        .HasColumnType("int");

                    b.Property<int>("MoniteurDeCoursId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("MoniteurDeCoursId");

                    b.ToTable("Occurences");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Piscine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CapaciteMaximale")
                        .HasColumnType("int");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Piscines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "560, rue Léon-Harmel",
                            CapaciteMaximale = 350,
                            CodePostal = "J2G3G7",
                            Nom = "Centre aquatique Desjardins de Granby",
                            Ville = "Granby"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "220, place Municipale",
                            CapaciteMaximale = 220,
                            CodePostal = "J2K1T4",
                            Nom = "Centre aquatique de Cowansville",
                            Ville = "Cowansville"
                        },
                        new
                        {
                            Id = 3,
                            Adresse = "850, rue Turcot",
                            CapaciteMaximale = 350,
                            CodePostal = "J2S1M2",
                            Nom = "Centre aquatique Desjardins de Saint-Hyacinthe",
                            Ville = "Saint-Hyacinthe"
                        });
                });

            modelBuilder.Entity("TP2_EFCORE.Models.PresenceCours", b =>
                {
                    b.Property<int>("OccurenceDuCoursId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.HasKey("OccurenceDuCoursId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("PresenceCours");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreationCompte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Cours", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.Cours", "CoursPrealable")
                        .WithMany()
                        .HasForeignKey("CoursPrealableId");

                    b.Navigation("CoursPrealable");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.CoursGroupe", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.Cours", "Cours")
                        .WithMany("Groupes")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2_EFCORE.Models.Moniteur", "Moniteur")
                        .WithMany("Groupes")
                        .HasForeignKey("MoniteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2_EFCORE.Models.Piscine", "Piscine")
                        .WithMany("Groupes")
                        .HasForeignKey("PiscineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Moniteur");

                    b.Navigation("Piscine");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Inscription", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.CoursGroupe", "Groupe")
                        .WithMany("Inscriptions")
                        .HasForeignKey("CoursGroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2_EFCORE.Models.Utilisateur", "Utilisateur")
                        .WithMany("Inscriptions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Moniteur", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.Utilisateur", "Utilisateur")
                        .WithOne("Moniteur")
                        .HasForeignKey("TP2_EFCORE.Models.Moniteur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.OccurenceCours", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.CoursGroupe", "Groupe")
                        .WithMany("Occurences")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2_EFCORE.Models.Moniteur", "Moniteur")
                        .WithMany("Occurences")
                        .HasForeignKey("MoniteurDeCoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");

                    b.Navigation("Moniteur");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.PresenceCours", b =>
                {
                    b.HasOne("TP2_EFCORE.Models.OccurenceCours", "Occurence")
                        .WithMany("PresencesCours")
                        .HasForeignKey("OccurenceDuCoursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TP2_EFCORE.Models.Utilisateur", "Utilisateur")
                        .WithMany("PresencesCours")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Occurence");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Cours", b =>
                {
                    b.Navigation("Groupes");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.CoursGroupe", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Occurences");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Moniteur", b =>
                {
                    b.Navigation("Groupes");

                    b.Navigation("Occurences");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.OccurenceCours", b =>
                {
                    b.Navigation("PresencesCours");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Piscine", b =>
                {
                    b.Navigation("Groupes");
                });

            modelBuilder.Entity("TP2_EFCORE.Models.Utilisateur", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Moniteur");

                    b.Navigation("PresencesCours");
                });
#pragma warning restore 612, 618
        }
    }
}
